language: node_js

env:
  - DATABASE_URL=postgresql://bantu:s0ty@t0b@n2@localhost:5432/greeting_test

node_js: "12"

before_script:
  - psql -c 'create database  greeting_test;' -U postgres
  - psql -U postgres -d greeting_test -a -f create-greet-table.sql

services:
  - postgresql
